# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
      - self-hosted
      - label-1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Docker login
        run: |
          docker login -u ${{ secrets.NEXUS_USERNAME }} -p ${{ secrets.NEXUS_PASSWORD }} ${{ vars.NEXUS_REPO }}

      # Runs a set of commands using the runners shell
      - name: Run Building Docker image
        run: |
          cd $GITHUB_WORKSPACE/build
          docker build -t ${{ vars.NEXUS_REPO }}/sri-appone .
      - name: Run Pushing Docker image
        run: |
          docker push ${{ vars.NEXUS_REPO }}/sri-appone:latest
      - name: Helm package
        run: |
          helm package -d $GITHUB_WORKSPACE/helm/ $GITHUB_WORKSPACE/helm/sri-appone
          curl -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} https://nexus.devopsodia.com/repository/devopsodia-helm/ --upload-file $GITHUB_WORKSPACE/helm/sri-appone-1.0.0.tgz -v
      - name: Deploy Helm chart on Kubernetes cluster
        run: |
          #helm uninstall sri-appone -n sriapp
          helm install sri-appone $GITHUB_WORKSPACE/helm/sri-appone-1.0.0.tgz -n sriapp
